INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('1', '1', '2016-04-14 10:00', 'Order Created', 'Create');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('2', '1', '2016-04-14 12:00', 'Order Picked and Packed', 'Packed');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('6', '1', '2016-04-18 09:10', 'Order Dispatched', 'Dispatch');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('11', '1', '2016-05-01 00:00', 'Full Payment Received', 'Payment');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('3', '2', '2016-04-15 12:15', 'Order Created', 'Create');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('4', '2', '2016-04-15 14:20', 'Order Picked and Packed', 'Packed');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('5', '2', '2016-04-16 09:10', 'Order Dispatched', 'Dispatch');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('13', '2', '2016-05-03 12:04', 'Partial Payment Received', 'Payment');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('16', '2', '2016-05-04 16:12', 'Return Received', 'Return');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('7', '3', '2016-04-19 08:20', 'Order Created', 'Create');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('18', '3', '2016-05-04 16:31', 'Order Packed', 'Packed');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('19', '3', '2016-05-04 16:32', 'Order Dispatched', 'Dispatch');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('24', '3', '2016-05-08 00:00', 'Full Payment received ', 'Payment');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('8', '4', '2016-04-25 16:00', 'Order Packed', 'Packed');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('9', '4', '2016-04-29 17:00', 'Order Dispatched', 'Dispatch');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('20', '4', '2016-05-05 09:20', 'Full Payment received ', 'Payment');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('10', '5', '2016-05-01 00:00', 'Order Created', 'Create');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('12', '5', '2016-05-02 00:00', 'Order Dispatched', 'Dispatch');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('21', '5', '2016-05-05 09:21', 'Full Payment received ', 'Payment');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('14', '6', '2016-05-04 10:30', 'Order Created', 'Create');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('15', '6', '2016-05-04 15:24', 'Order Packed', 'Packed');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('17', '6', '2016-05-04 16:30', 'Order Dispatched', 'Dispatch');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('25', '6', '2016-05-09 15:10', 'Full Return', 'Return');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('22', '7', '2016-05-07 08:45', 'Order Created', 'Create');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('23', '7', '2016-05-07 10:35', 'Order Packed', 'Packed');
INSERT INTO `mydb`.`sales_order_event` (`sales_event_id`, `Sales_Order_sales_id`, `time_stamp`, `description`, `type`) VALUES ('26', '7', '2016-05-10 10:00', 'Full Payment Received', 'Payment');
